[package]
name = "rust_algorithms"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4.0"

[[example]]
name = "leibniz"
path = "examples/pi/leibniz_pi.rs"

[[example]]
name = "machin"
path = "examples/pi/machin_pi.rs"
